version: '3'
services:
  db1:
    image: postgres:13
    environment:
      POSTGRES_DB: warehouse1
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: pass4user1
    volumes:
      - ./init-db1.sql:/docker-entrypoint-initdb.d/init-db1.sql
    networks:
      - app-network
    ports:
      - "5432:5432"

  db2:
    image: postgres:13
    environment:
      POSTGRES_DB: warehouse2
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: pass4user1
    volumes:
      - ./init-db2.sql:/docker-entrypoint-initdb.d/init-db2.sql
    networks:
      - app-network
    ports:
      - "5433:5432"

  app:
    build: .
    depends_on:
      - db1
      - db2
    volumes:
      - ./output:/app/output
      - ./app/main.py:/app/main.py
    environment:
      - POSTGRES_HOST_DB1=172.25.6.103
      - POSTGRES_HOST_DB2=172.25.6.103
      - POSTGRES_PORT1=5432
      - POSTGRES_PORT2=5433
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=pass4user1
      - POSTGRES_DB1=warehouse1
      - POSTGRES_DB2=warehouse2
    networks:
      - app-network
#    tty: true
#    stdin_open: true

networks:
  app-network:
    driver: bridge